"""initial schema

Revision ID: 48781aaa36b9
Revises: 
Create Date: 2026-06-15 13:30:14.031267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '48781aaa36b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('lga_code', sa.String(length=20), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lga_code')
    )
    # idx_lgas_centroid and idx_lgas_geometry are created by GeoAlchemy2 automatically
    op.create_index('ix_lgas_name_state', 'lgas', ['name', 'state'], unique=True)
    op.create_index('ix_lgas_state', 'lgas', ['state'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lga_id', sa.UUID(), nullable=True),
    sa.Column('acled_id', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('sub_event_type', sa.String(length=100), nullable=True),
    sa.Column('actor1', sa.String(length=200), nullable=True),
    sa.Column('actor2', sa.String(length=200), nullable=True),
    sa.Column('inter1', sa.String(length=10), nullable=True),
    sa.Column('inter2', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('admin1', sa.String(length=100), nullable=True),
    sa.Column('admin2', sa.String(length=100), nullable=True),
    sa.Column('admin3', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_precision', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('source_scale', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acled_id')
    )
    op.create_index('ix_incidents_acled_id', 'incidents', ['acled_id'], unique=False)
    op.create_index('ix_incidents_admin1', 'incidents', ['admin1'], unique=False)
    op.create_index('ix_incidents_event_date', 'incidents', ['event_date'], unique=False)
    op.create_index('ix_incidents_event_type', 'incidents', ['event_type'], unique=False)
    op.create_index('ix_incidents_lga_id', 'incidents', ['lga_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lga_id', sa.UUID(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_state', sa.String(length=50), nullable=True),
    sa.Column('extracted_lga', sa.String(length=100), nullable=True),
    sa.Column('security_relevant', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scrape_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_extracted_state', 'news_articles', ['extracted_state'], unique=False)
    op.create_index('ix_news_lga_id', 'news_articles', ['lga_id'], unique=False)
    op.create_index('ix_news_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_security_relevant', 'news_articles', ['security_relevant'], unique=False)
    op.create_index('ix_news_source', 'news_articles', ['source'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lga_id', sa.UUID(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('incident_frequency_score', sa.Float(), nullable=True),
    sa.Column('incident_trend_score', sa.Float(), nullable=True),
    sa.Column('news_sentiment_score', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_scores_level', 'risk_scores', ['level'], unique=False)
    op.create_index('ix_risk_scores_lga_date', 'risk_scores', ['lga_id', 'score_date', 'is_forecast'], unique=True)
    op.create_index('ix_risk_scores_lga_id', 'risk_scores', ['lga_id'], unique=False)
    op.create_index('ix_risk_scores_score_date', 'risk_scores', ['score_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_scores_score_date', table_name='risk_scores')
    op.drop_index('ix_risk_scores_lga_id', table_name='risk_scores')
    op.drop_index('ix_risk_scores_lga_date', table_name='risk_scores')
    op.drop_index('ix_risk_scores_level', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_news_source', table_name='news_articles')
    op.drop_index('ix_news_security_relevant', table_name='news_articles')
    op.drop_index('ix_news_published_at', table_name='news_articles')
    op.drop_index('ix_news_lga_id', table_name='news_articles')
    op.drop_index('ix_news_extracted_state', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_incidents_lga_id', table_name='incidents')
    op.drop_index('ix_incidents_event_type', table_name='incidents')
    op.drop_index('ix_incidents_event_date', table_name='incidents')
    op.drop_index('ix_incidents_admin1', table_name='incidents')
    op.drop_index('ix_incidents_acled_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_lgas_state', table_name='lgas')
    op.drop_index('ix_lgas_name_state', table_name='lgas')
    # idx_lgas_geometry and idx_lgas_centroid dropped automatically with table
    op.drop_table('lgas')
    # ### end Alembic commands ###
